 artist = new Array;

 
artist[0] = new Object;
artist[0].name = "JKRIV"
artist[0].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
artist[0].location = "Paris, France"
artist[0].territory = "Somewhere over the rainbow"
artist[0].img1 = "/grid/jkriv.jpg"
artist[0].img2 = "/img/jkriv.jpg"

 artist[1] = new Object;
 artist[1].name = "LOVEBIRDS"
 artist[1].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[1].location = "Paris, France"
 artist[1].territory = "Somewhere over the rainbow"
 artist[1].img1 = "/grid/lovebirds.jpg"
 artist[1].img2 = "/img/lovebirds.jpg"
 
 artist[2] = new Object;
 artist[2].name = "RON BASEJAM"
 artist[2].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[2].location = "Paris, France"
 artist[2].territory = "Somewhere over the rainbow"
 artist[2].img1 = "/grid/ron-basejam.jpg"
 artist[2].img2 = "/img/ron-basejam.jpg"
 
 artist[3] = new Object;
 artist[3].name = "HOT TODDY"
 artist[3].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[3].location = "Paris, France"
 artist[3].territory = "Somewhere over the rainbow"
 artist[3].img1 = "/grid/hot-toddy.jpg"
 artist[3].img2 = "/img/hot-toddy.jpg"
 
 artist[4] = new Object;
 artist[4].name = "CRAZY P"
 artist[4].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[4].location = "Paris, France"
 artist[4].territory = "Somewhere over the rainbow"
 artist[4].img1 = "/grid/crazy-p.jpg"
 artist[4].img2 = "/img/crazy-p.jpg"
 
 artist[5] = new Object;
 artist[5].name = "LUKE SOLOMON"
 artist[5].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[5].location = "Paris, France"
 artist[5].territory = "Somewhere over the rainbow"
 artist[5].img1 = "/grid/luke-solomon.jpg"
 artist[5].img2 = "/img/luke-solomon.jpg"
 
 artist[6] = new Object;
 artist[6].name = "KON"
 artist[6].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[6].location = "Paris, France"
 artist[6].territory = "Somewhere over the rainbow"
 artist[6].img1 = "/grid/kon.jpg"
 artist[6].img2 = "/img/kon.jpg"
 
 artist[7] = new Object;
 artist[7].name = "MOPLEN"
 artist[7].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[7].location = "Paris, France"
 artist[7].territory = "Somewhere over the rainbow"
 artist[7].img1 = "/grid/moplen.jpg"
 artist[7].img2 = "/img/moplen.jpg"
 
 artist[8] = new Object;
 artist[8].name = "SLEAZY BEATS SOUNDSYSTEM"
 artist[8].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[8].location = "Paris, France"
 artist[8].territory = "Somewhere over the rainbow"
 artist[8].img1 = "/grid/sleazy-beats-soundsystem.jpg"
 artist[8].img2 = "/img/sleazy-beats-soundsystem.jpg"
 
 artist[9] = new Object;
 artist[9].name = "ELI ESCOBAR"
 artist[9].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[9].location = "Paris, France"
 artist[9].territory = "Somewhere over the rainbow"
 artist[9].img1 = "/grid/eli-escobar.jpg"
 artist[9].img2 = "/img/eli-escobar.jpg"
 
 artist[10] = new Object;
 artist[10].name = "MARTIN HAYNES"
 artist[10].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[10].location = "Paris, France"
 artist[10].territory = "Somewhere over the rainbow"
 artist[10].img1 = "/grid/martin-hayes.jpg"
 artist[10].img2 = "/img/martin-hayes.jpg"
 
 artist[11] = new Object;
 artist[11].name = "LABEUZ"
 artist[11].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[11].location = "Paris, France"
 artist[11].territory = "Somewhere over the rainbow"
 artist[11].img1 = "/grid/labeuz.jpg"
 artist[11].img2 = "/img/labeuz.jpg"
 
 artist[12] = new Object;
 artist[12].name = "QWESTLIFE"
 artist[12].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[12].location = "Paris, France"
 artist[12].territory = "Somewhere over the rainbow"
 artist[12].img1 = "/grid/qwestlife.jpg"
 artist[12].img2 = "/img/qwestlife.jpg"
 
 artist[13] = new Object;
 artist[13].name = "Sleazy McQueen"
 artist[13].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[13].location = "Paris, France"
 artist[13].territory = "Somewhere over the rainbow"
 artist[13].img1 = "/grid/sleazy-mcqueen.jpg"
 artist[13].img2 = "/img/sleazy-mcqueen.jpg"
 
 artist[14] = new Object;
 artist[14].name = "FRED EVERYTHING"
 artist[14].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[14].location = "Paris, France"
 artist[14].territory = "Somewhere over the rainbow"
 artist[14].img1 = "/grid/fred-everything.jpg"
 artist[14].img2 = "/img/fred-everything.jpg"
 
 artist[15] = new Object;
 artist[15].name = "Rainer Trueby"
 artist[15].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[15].location = "Paris, France"
 artist[15].territory = "Somewhere over the rainbow"
 artist[15].img1 = "/grid/rainer-trueby.jpg"
 artist[15].img2 = "/img/rainer-trueby.jpg"
 
 artist[16] = new Object;
 artist[16].name = "Lay Far"
 artist[16].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[16].location = "Paris, France"
 artist[16].territory = "Somewhere over the rainbow"
 artist[16].img1 = "/grid/lay-far.jpg"
 artist[16].img2 = "/img/lay-far.jpg"
 
 artist[17] = new Object;
 artist[17].name = "Razor N Tape"
 artist[17].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[17].location = "Paris, France"
 artist[17].territory = "Somewhere over the rainbow"
 artist[17].img1 = "/grid/razor-n-tape.jpg"
 artist[17].img2 = "/img/razor-n-tape.jpg"
 
 artist[18] = new Object;
 artist[18].name = "Wolf Music"
 artist[18].description = eschtml("Seven albums, a career spanning over 20 years and yet Crazy P remain stronger and more relevant than ever. Funny how the tides of time turn, and how the sounds of a typically British type of house and disco are now more du jour then ever before. Way before the rise in prominence of disco, house and soulful pop Crazy P have spearheaded the revival (and perpetuation) of these sounds since 1997.\n\nTheir seventh album ‘Walk Dance Talk Sing’ was released in 2015, to great acclaim, on their own imprint and in partnership with !K7. In the time since the songwriting, production, and performing nucleus of Danielle Moore, Chris Todd, and James Baron have been constantly touring with their DJ and Soundsystem sets and live band shows. Regarded as one of dance music’s finest and genuinely live, performers out there. \n\nCrazy P have managed to both uphold the heritage of soul, musicianship and songwriting that is an essential part of the fabric of house and disco. They stay current, letting those fundamental elements of the sound inform and mark out their take on the club floors and younger audiences that they consistently turn inside out. Their never diminishing love of a dancefloor sits firmly alongside their immaculate craft of writing and production. New audiences are, without exception, blown away the first time they see a Crazy P live show.\n\n2016’s touring schedule took the band around the world, culminating with a live show in Bali, streamed on the prestigious Boiler Room. This year Crazy P proudly released their ‘Truelight’ EP on the legendary Classic. This was followed by a summer of festivals and an ambition realised when the band recently performed live at Londons Roundhouse.\n\nIt is widely expected we will see new material emerge in 2018. The anticipation is set and the bar is high…")
 artist[18].location = "Paris, France"
 artist[18].territory = "Somewhere over the rainbow"
 artist[18].img1 = "/grid/wolf-music.jpg"
 artist[18].img2 = "/img/wolf-music.jpg"


artist.forEach(el => {
	var sql = 'INSERT INTO `artists` (`name`, `description`, `location`, `territory`, `img1`, `img2`) VALUES (?, ?, ?, ?, ?, ?)';
		    con.query(sql, [el.name, el.description, el.location, el.territory, el.img1, el.img2], (err) => { if (err) tools.error(err); })
})









